### ISSUE TITLE
Node states not updating

### ISSUE THREAD

**Issue by rrdbn4** [rrdbn4/5800Project#1]
The nodes are flying off the grid. This is due the integer division and rounding errors. I would suggest making the updates more often and with smaller movement deltas. 

I'm not sure why switching to paintComponent() in JPanel broke the node movement, but it was necessary to get rid of that flashing issue.

**Comment by hmbwbc** [comment]
I was thinking we were going to implement it like the sorting project in
GUI. We used threads to call the repaint method.

**Comment by hmbwbc** [comment]
Nevermind working with JFrame is different so I guess we're forced to use
paintComponent?

**Comment by hmbwbc** [comment]
Hey did anyone change the size of y1 and y3?

**Comment by mdlkwd** [comment]
I did not. Sorry, I haven't had a chance to work on the project due to
Easter.

**Comment by hmbwbc** [comment]
Hey can I make x1, x2, etc all constants instead of relying on getInsets?
The problem with the gui is that the distances are prime numbers ( 337) so
it works if it moves at 1 but that's really slow.

**Comment by hmbwbc** [comment]
This fixes the problem:

  x1 = getInsets().left + (int)(800 \* 0.15);
      x2 = getInsets().left + (int)(800 \* 0.35);
      x3 = getInsets().left + (int)(800 \* 0.65);
      x4 = getInsets().left + (int)(800 \* 0.85);
      y1 = getInsets().top + (int)(600 \* 0.2);
      y2 = getInsets().top + (int)(600 \* 0.5);
      y3 = getInsets().top + (int)(600 \* 0.8);

**Comment by hmbwbc** [comment]
CORRECTION:

(This is better written code)

  int height=600;
  int width=800;

```
  x1 = getInsets().left + (int)(width * 0.15);
  x2 = getInsets().left + (int)(width * 0.35);
  x3 = getInsets().left + (int)(width * 0.65);
  x4 = getInsets().left + (int)(width * 0.85);
  y1 = getInsets().top + (int)(height * 0.2);
  y2 = getInsets().top + (int)(height * 0.5);
  y3 = getInsets().top + (int)(height * 0.8);
```

**Comment by rrdbn4** [comment]
Sorry I missed all the previous replies. That code looks fine. You could
also make the increment 1 and then set the timer to update every 20ms
instead of every 200ms. The parts that worried me were the lines in
updateNode() such as if(node.x==x1 && node.y==y1). This is only going to be
triggered if the node hits that point exactly. It won't know if the nodes
flies past that point like it's doing now. I hope I'm explaining this
correctly.

On Sun, Apr 5, 2015 at 7:03 PM, hmbwbc notifications@github.com wrote:

> CORRECTION:
> 
> (This is better written code)
> 
> int height=600;
> int width=800;
> 
> x1 = getInsets().left + (int)(width \* 0.15);
> x2 = getInsets().left + (int)(width \* 0.35);
> x3 = getInsets().left + (int)(width \* 0.65);
> x4 = getInsets().left + (int)(width \* 0.85);
> y1 = getInsets().top + (int)(height \* 0.2);
> y2 = getInsets().top + (int)(height \* 0.5);
> y3 = getInsets().top + (int)(height \* 0.8);
> 
> On Sun, Apr 5, 2015 at 7:02 PM, Holly Busken hmbwbc@mst.edu wrote:
> 
> > This fixes the problem:
> > 
> > x1 = getInsets().left + (int)(800 \* 0.15);
> > x2 = getInsets().left + (int)(800 \* 0.35);
> > x3 = getInsets().left + (int)(800 \* 0.65);
> > x4 = getInsets().left + (int)(800 \* 0.85);
> > y1 = getInsets().top + (int)(600 \* 0.2);
> > y2 = getInsets().top + (int)(600 \* 0.5);
> > y3 = getInsets().top + (int)(600 \* 0.8);
> > 
> > On Sun, Apr 5, 2015 at 6:53 PM, Holly Busken hmbwbc@mst.edu wrote:
> > 
> > > Hey can I make x1, x2, etc all constants instead of relying on
> > > getInsets?
> > > The problem with the gui is that the distances are prime numbers ( 337)
> > > so
> > > it works if it moves at 1 but that's really slow.
> > > 
> > > On Sun, Apr 5, 2015 at 6:50 PM, mdlkwd notifications@github.com
> > > wrote:
> > > 
> > > > I did not. Sorry, I haven't had a chance to work on the project due to
> > > > Easter.
> > > > 
> > > > On Sunday, April 5, 2015, hmbwbc notifications@github.com wrote:
> > > > 
> > > > > Hey did anyone change the size of y1 and y3?
> > > > > 
> > > > > On Sun, Apr 5, 2015 at 6:36 PM, Holly Busken <hmbwbc@mst.edu
> > > > > <javascript:_e(%7B%7D,'cvml','hmbwbc@mst.edu');>> wrote:
> > > > > 
> > > > > > Nevermind working with JFrame is different so I guess we're forced
> > > > > > to use
> > > > > > paintComponent?
> > > > > > 
> > > > > > On Sun, Apr 5, 2015 at 5:17 PM, Holly Busken <hmbwbc@mst.edu
> > > > > > <javascript:_e(%7B%7D,'cvml','hmbwbc@mst.edu');>> wrote:
> > > > > > 
> > > > > > > I was thinking we were going to implement it like the sorting
> > > > > > > project in
> > > > > > > GUI. We used threads to call the repaint method.
> > > > > > > 
> > > > > > > On Sat, Apr 4, 2015 at 10:25 PM, rrdbn4 <notifications@github.com
> > > > > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > > > > > > 
> > > > > > > > The nodes are flying off the grid. This is due the integer
> > > > > > > > division and
> > > > > > > > rounding errors. I would suggest making the updates more often
> > > > > > > > and
> > > > > > > > with
> > > > > > > > smaller movement deltas.
> > > > > > > > 
> > > > > > > > I'm not sure why switching to paintComponent() in JPanel broke
> > > > > > > > the
> > > > > > > > node
> > > > > > > > movement, but it was necessary to get rid of that flashing issue.
> > > > > > > > 
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > https://github.com/rrdbn4/5800Project/issues/1.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > > > https://github.com/rrdbn4/5800Project/issues/1#issuecomment-89869859
> > > > > .
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/rrdbn4/5800Project/issues/1#issuecomment-89869939
> > > > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rrdbn4/5800Project/issues/1#issuecomment-89870802.

## 

Robert Dunn
Computer Science - Missouri S&T

**Comment by hmbwbc** [comment]
If it increments and decrements in the correct increments (factors of the
number) it will always hit the number

**Comment by hmbwbc** [comment]
I could put checks in there to see if it increments more than it's multiple
( if it does then it's going past the point it needs to be at)

**Comment by rrdbn4** [comment]
It would be a good idea to put in those checks. It isn't incrementing or
decrementing correctly with the code I have. Also, those checks would allow
the window to be resized.

On Sun, Apr 5, 2015 at 8:00 PM, hmbwbc notifications@github.com wrote:

> I could put checks in there to see if it increments more than it's multiple
> ( if it does then it's going past the point it needs to be at)
> 
> On Sun, Apr 5, 2015 at 7:59 PM, Holly Busken hmbwbc@mst.edu wrote:
> 
> > If it increments and decrements in the correct increments (factors of the
> > number) it will always hit the number
> > 
> > On Sun, Apr 5, 2015 at 7:58 PM, rrdbn4 notifications@github.com wrote:
> > 
> > > Sorry I missed all the previous replies. That code looks fine. You could
> > > also make the increment 1 and then set the timer to update every 20ms
> > > instead of every 200ms. The parts that worried me were the lines in
> > > updateNode() such as if(node.x==x1 && node.y==y1). This is only going to
> > > be
> > > triggered if the node hits that point exactly. It won't know if the
> > > nodes
> > > flies past that point like it's doing now. I hope I'm explaining this
> > > correctly.
> > > 
> > > On Sun, Apr 5, 2015 at 7:03 PM, hmbwbc notifications@github.com
> > > wrote:
> > > 
> > > > CORRECTION:
> > > > 
> > > > (This is better written code)
> > > > 
> > > > int height=600;
> > > > int width=800;
> > > > 
> > > > x1 = getInsets().left + (int)(width \* 0.15);
> > > > x2 = getInsets().left + (int)(width \* 0.35);
> > > > x3 = getInsets().left + (int)(width \* 0.65);
> > > > x4 = getInsets().left + (int)(width \* 0.85);
> > > > y1 = getInsets().top + (int)(height \* 0.2);
> > > > y2 = getInsets().top + (int)(height \* 0.5);
> > > > y3 = getInsets().top + (int)(height \* 0.8);
> > > > 
> > > > On Sun, Apr 5, 2015 at 7:02 PM, Holly Busken hmbwbc@mst.edu wrote:
> > > > 
> > > > > This fixes the problem:
> > > > > 
> > > > > x1 = getInsets().left + (int)(800 \* 0.15);
> > > > > x2 = getInsets().left + (int)(800 \* 0.35);
> > > > > x3 = getInsets().left + (int)(800 \* 0.65);
> > > > > x4 = getInsets().left + (int)(800 \* 0.85);
> > > > > y1 = getInsets().top + (int)(600 \* 0.2);
> > > > > y2 = getInsets().top + (int)(600 \* 0.5);
> > > > > y3 = getInsets().top + (int)(600 \* 0.8);
> > > > > 
> > > > > On Sun, Apr 5, 2015 at 6:53 PM, Holly Busken hmbwbc@mst.edu
> > > > > wrote:
> > > > > 
> > > > > > Hey can I make x1, x2, etc all constants instead of relying on
> > > > > > getInsets?
> > > > > > The problem with the gui is that the distances are prime numbers (
> > > > > > 337)
> > > > > > so
> > > > > > it works if it moves at 1 but that's really slow.
> > > > > > 
> > > > > > On Sun, Apr 5, 2015 at 6:50 PM, mdlkwd notifications@github.com
> > > > > > wrote:
> > > > > > 
> > > > > > > I did not. Sorry, I haven't had a chance to work on the project
> > > > > > > due
> > > > > > > to
> > > > > > > Easter.
> > > > > > > 
> > > > > > > On Sunday, April 5, 2015, hmbwbc notifications@github.com
> > > > > > > wrote:
> > > > > > > 
> > > > > > > > Hey did anyone change the size of y1 and y3?
> > > > > > > > 
> > > > > > > > On Sun, Apr 5, 2015 at 6:36 PM, Holly Busken <hmbwbc@mst.edu
> > > > > > > > <javascript:_e(%7B%7D,'cvml','hmbwbc@mst.edu');>> wrote:
> > > > > > > > 
> > > > > > > > > Nevermind working with JFrame is different so I guess we're
> > > > > > > > > forced
> > > > > > > > > to use
> > > > > > > > > paintComponent?
> > > > > > > > > 
> > > > > > > > > On Sun, Apr 5, 2015 at 5:17 PM, Holly Busken <hmbwbc@mst.edu
> > > > > > > > > <javascript:_e(%7B%7D,'cvml','hmbwbc@mst.edu');>> wrote:
> > > > > > > > > 
> > > > > > > > > > I was thinking we were going to implement it like the sorting
> > > > > > > > > > project in
> > > > > > > > > > GUI. We used threads to call the repaint method.
> > > > > > > > > > 
> > > > > > > > > > On Sat, Apr 4, 2015 at 10:25 PM, rrdbn4 <
> > > > > > > > > > notifications@github.com
> > > > > > > > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > > > > > > > > > wrote:
> > > > > > > > > > 
> > > > > > > > > > > The nodes are flying off the grid. This is due the integer
> > > > > > > > > > > division and
> > > > > > > > > > > rounding errors. I would suggest making the updates more
> > > > > > > > > > > often
> > > > > > > > > > > and
> > > > > > > > > > > with
> > > > > > > > > > > smaller movement deltas.
> > > > > > > > > > > 
> > > > > > > > > > > I'm not sure why switching to paintComponent() in JPanel
> > > > > > > > > > > broke
> > > > > > > > > > > the
> > > > > > > > > > > node
> > > > > > > > > > > movement, but it was necessary to get rid of that flashing
> > > > > > > > > > > issue.
> > > > > > > > > > > 
> > > > > > > > > > > —
> > > > > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > > > > https://github.com/rrdbn4/5800Project/issues/1.
> > > > > > > > 
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > <
> > > > > > > > https://github.com/rrdbn4/5800Project/issues/1#issuecomment-89869859
> > > > > > > > .
> > > > > > > 
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <
> > > > > > > https://github.com/rrdbn4/5800Project/issues/1#issuecomment-89869939
> > > > > > > .
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/rrdbn4/5800Project/issues/1#issuecomment-89870802
> > > > .
> > > 
> > > ## 
> > > 
> > > Robert Dunn
> > > Computer Science - Missouri S&T
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/rrdbn4/5800Project/issues/1#issuecomment-89876825.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rrdbn4/5800Project/issues/1#issuecomment-89877310.

## 

Robert Dunn
Computer Science - Missouri S&T

**Comment by hmbwbc** [comment]
I'll commit the code I have!

**Comment by rrdbn4** [comment]
Oh. I didn't realize I was working with old code. Thanks!

On Sun, Apr 5, 2015 at 8:03 PM, hmbwbc notifications@github.com wrote:

> I'll commit the code I have!
> 
> On Sun, Apr 5, 2015 at 8:03 PM, rrdbn4 notifications@github.com wrote:
> 
> > It would be a good idea to put in those checks. It isn't incrementing or
> > decrementing correctly with the code I have. Also, those checks would
> > allow
> > the window to be resized.
> > 
> > On Sun, Apr 5, 2015 at 8:00 PM, hmbwbc notifications@github.com wrote:
> > 
> > > I could put checks in there to see if it increments more than it's
> > > multiple
> > > ( if it does then it's going past the point it needs to be at)
> > > 
> > > On Sun, Apr 5, 2015 at 7:59 PM, Holly Busken hmbwbc@mst.edu wrote:
> > > 
> > > > If it increments and decrements in the correct increments (factors of
> > > > the
> > > > number) it will always hit the number
> > > > 
> > > > On Sun, Apr 5, 2015 at 7:58 PM, rrdbn4 notifications@github.com
> > > > wrote:
> > > > 
> > > > > Sorry I missed all the previous replies. That code looks fine. You
> > > > > could
> > > > > also make the increment 1 and then set the timer to update every
> > > > > 20ms
> > > > > instead of every 200ms. The parts that worried me were the lines in
> > > > > updateNode() such as if(node.x==x1 && node.y==y1). This is only
> > > > > going
> > > > > to
> > > > > be
> > > > > triggered if the node hits that point exactly. It won't know if the
> > > > > nodes
> > > > > flies past that point like it's doing now. I hope I'm explaining
> > > > > this
> > > > > correctly.
> > > > > 
> > > > > On Sun, Apr 5, 2015 at 7:03 PM, hmbwbc notifications@github.com
> > > > > wrote:
> > > > > 
> > > > > > CORRECTION:
> > > > > > 
> > > > > > (This is better written code)
> > > > > > 
> > > > > > int height=600;
> > > > > > int width=800;
> > > > > > 
> > > > > > x1 = getInsets().left + (int)(width \* 0.15);
> > > > > > x2 = getInsets().left + (int)(width \* 0.35);
> > > > > > x3 = getInsets().left + (int)(width \* 0.65);
> > > > > > x4 = getInsets().left + (int)(width \* 0.85);
> > > > > > y1 = getInsets().top + (int)(height \* 0.2);
> > > > > > y2 = getInsets().top + (int)(height \* 0.5);
> > > > > > y3 = getInsets().top + (int)(height \* 0.8);
> > > > > > 
> > > > > > On Sun, Apr 5, 2015 at 7:02 PM, Holly Busken hmbwbc@mst.edu
> > > > > > wrote:
> > > > > > 
> > > > > > > This fixes the problem:
> > > > > > > 
> > > > > > > x1 = getInsets().left + (int)(800 \* 0.15);
> > > > > > > x2 = getInsets().left + (int)(800 \* 0.35);
> > > > > > > x3 = getInsets().left + (int)(800 \* 0.65);
> > > > > > > x4 = getInsets().left + (int)(800 \* 0.85);
> > > > > > > y1 = getInsets().top + (int)(600 \* 0.2);
> > > > > > > y2 = getInsets().top + (int)(600 \* 0.5);
> > > > > > > y3 = getInsets().top + (int)(600 \* 0.8);
> > > > > > > 
> > > > > > > On Sun, Apr 5, 2015 at 6:53 PM, Holly Busken hmbwbc@mst.edu
> > > > > > > wrote:
> > > > > > > 
> > > > > > > > Hey can I make x1, x2, etc all constants instead of relying on
> > > > > > > > getInsets?
> > > > > > > > The problem with the gui is that the distances are prime
> > > > > > > > numbers
> > > > > > > > (
> > > > > > > > 337)
> > > > > > > > so
> > > > > > > > it works if it moves at 1 but that's really slow.
> > > > > > > > 
> > > > > > > > On Sun, Apr 5, 2015 at 6:50 PM, mdlkwd <
> > > > > > > > notifications@github.com
> > > > > > 
> > > > > > wrote:
> > > > > > 
> > > > > > > > > I did not. Sorry, I haven't had a chance to work on the
> > > > > > > > > project
> > > > > > > > > due
> > > > > > > > > to
> > > > > > > > > Easter.
> > > > > > > > > 
> > > > > > > > > On Sunday, April 5, 2015, hmbwbc notifications@github.com
> > > > > > > > > wrote:
> > > > > > > > > 
> > > > > > > > > > Hey did anyone change the size of y1 and y3?
> > > > > > > > > > 
> > > > > > > > > > On Sun, Apr 5, 2015 at 6:36 PM, Holly Busken <
> > > > > > > > > > hmbwbc@mst.edu
> > > > > > > > > > <javascript:_e(%7B%7D,'cvml','hmbwbc@mst.edu');>> wrote:
> > > > > > > > > > 
> > > > > > > > > > > Nevermind working with JFrame is different so I guess
> > > > > > > > > > > we're
> > > > > > > > > > > forced
> > > > > > > > > > > to use
> > > > > > > > > > > paintComponent?
> > > > > > > > > > > 
> > > > > > > > > > > On Sun, Apr 5, 2015 at 5:17 PM, Holly Busken <
> > > > > > > > > > > hmbwbc@mst.edu
> > > > > > > > > > > <javascript:_e(%7B%7D,'cvml','hmbwbc@mst.edu');>> wrote:
> > > > > > > > > > > 
> > > > > > > > > > > > I was thinking we were going to implement it like the
> > > > > > > > > > > > sorting
> > > > > > > > > > > > project in
> > > > > > > > > > > > GUI. We used threads to call the repaint method.
> > > > > > > > > > > > 
> > > > > > > > > > > > On Sat, Apr 4, 2015 at 10:25 PM, rrdbn4 <
> > > > > > > > > > > > notifications@github.com
> > > > > > > > > > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > > > > > > > > > > > wrote:
> > > > > > > > > > > > 
> > > > > > > > > > > > > The nodes are flying off the grid. This is due the
> > > > > > > > > > > > > integer
> > > > > > > > > > > > > division and
> > > > > > > > > > > > > rounding errors. I would suggest making the updates more
> > > > > > > > > > > > > often
> > > > > > > > > > > > > and
> > > > > > > > > > > > > with
> > > > > > > > > > > > > smaller movement deltas.
> > > > > > > > > > > > > 
> > > > > > > > > > > > > I'm not sure why switching to paintComponent() in JPanel
> > > > > > > > > > > > > broke
> > > > > > > > > > > > > the
> > > > > > > > > > > > > node
> > > > > > > > > > > > > movement, but it was necessary to get rid of that
> > > > > > > > > > > > > flashing
> > > > > > > > > > > > > issue.
> > > > > > > > > > > > > 
> > > > > > > > > > > > > —
> > > > > > > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > > > > > > https://github.com/rrdbn4/5800Project/issues/1.
> > > > > > > > > > 
> > > > > > > > > > —
> > > > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > > > <
> > > > > > 
> > > > > > https://github.com/rrdbn4/5800Project/issues/1#issuecomment-89869859
> > > > > > 
> > > > > > > > > > .
> > > > > > > > > 
> > > > > > > > > —
> > > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > > <
> > > > > 
> > > > > https://github.com/rrdbn4/5800Project/issues/1#issuecomment-89869939
> > > > > 
> > > > > > > .
> > > > > > > 
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > > > > > https://github.com/rrdbn4/5800Project/issues/1#issuecomment-89870802
> > > > > > .
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Robert Dunn
> > > > > Computer Science - Missouri S&T
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > > > https://github.com/rrdbn4/5800Project/issues/1#issuecomment-89876825
> > > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/rrdbn4/5800Project/issues/1#issuecomment-89877310
> > > .
> > 
> > ## 
> > 
> > Robert Dunn
> > Computer Science - Missouri S&T
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/rrdbn4/5800Project/issues/1#issuecomment-89877397.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rrdbn4/5800Project/issues/1#issuecomment-89877478.

## 

Robert Dunn
Computer Science - Missouri S&T

**Comment by hmbwbc** [comment]
it's uploaded now!
